import Head from 'next/head';
import Layout from '../components/Layout/Layout';
import Users from '../components/Users/Users';


export default function Home({data}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Layout>
          <Users data={data} />
        </Layout>
    </div>
  )
}


export const getStaticProps = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/users');
  const data = await res.json();
  return {
    props:{
      data,
    }
  }
}